### ISSUE TITLE
Incompatible with quilt

### ISSUE THREAD

**Issue by RinixGG** [KaiAF/BetterHandBobbing#1]
Hello! Mod is incompatible with quilt loader, tested on quilt 0.17.7 and quilt 0.18.1-beta21
![изображение](https://user-images.githubusercontent.com/73175330/205488665-64d33bb9-e6c5-4528-9d39-812ea11dc1b1.png)

**Comment by KaiAF** [comment]
Fixed in [1.2](https://modrinth.com/mod/better-hand-bobbing/version/1.2)

**Comment by RinixGG** [comment]
> Fixed in [1.2](https://modrinth.com/mod/better-hand-bobbing/version/1.2)

Oh, 1.2 doesn't work too(
![изображение](https://user-images.githubusercontent.com/73175330/205497551-6bd0b1d0-afe2-42e3-a996-77c3f595d0ea.png)

**Comment by KaiAF** [comment]
Testing with Quilted Fabric API, it crashes. Without it, it should work. I'll look into fixing

**Comment by KaiAF** [comment]
*Should* be fixed here, https://modrinth.com/mod/better-hand-bobbing/version/1.2.1

**Comment by RinixGG** [comment]
> _Should_ be fixed here, https://modrinth.com/mod/better-hand-bobbing/version/1.2.1

Yes, now it works, but there is no button called hand bobbing
![изображение](https://user-images.githubusercontent.com/73175330/205503705-32db56b7-78c0-439e-8f4f-36f74277c727.png)

**Comment by KaiAF** [comment]
What mod effects the settings like that? And check sodium video settings?

**Comment by RinixGG** [comment]
> What mod effects the settings like that? And check sodium video settings?

Oh, sorry, I've checked the sodium video settings but didn't notice the button. Everything is ok.
