### ISSUE TITLE
use client environment to prevent server crashes

### ISSUE THREAD

**Issue by Linguardium** [KaiAF/BetterHandBobbing#13]
https://github.com/KaiAF/BetterHandBobbing/blob/29e729c3dd094017c24022b433264b9e807b9213/src/main/resources/fabric.mod.json#L13

since this mod is clientside only, i would suggest changing the environment here to "client" to prevent servers from trying to load it and crashing

**Comment by KaiAF** [comment]
fixed, [ghost updated 1.6.3](https://modrinth.com/mod/better-hand-bobbing/version/1.6.3)
