### ISSUE TITLE
Option enabled itself after re-launching the game

### ISSUE THREAD

**Issue by Scarlaid** [KaiAF/BetterHandBobbing#2]
Turn off the Hand Bobbing, turn off the game, re-launch it, the option will be enabled by itself
A video could help: https://streamable.com/nv3i6q

Forgot to inform that I used Shared Resources to change the directory of some game's folders, hope that related

**Comment by KaiAF** [comment]
Looking at the code the setting is not being saved in the options.txt file. Will fix soon

**Comment by KaiAF** [comment]
Fixed https://modrinth.com/mod/better-hand-bobbing/version/1.2.2
