### ISSUE TITLE
1.19.4?

### ISSUE THREAD

**Issue by Xrey274** [KaiAF/BetterHandBobbing#3]
Game crashes with current 1.3 version on Modrinth.

**Comment by KaiAF** [comment]
send a crash log

**Comment by Xrey274** [comment]
Oops, sorry I was using the old version. You should put the new one in feature so people don't get confused. 
![image](https://github.com/KaiAF/BetterHandBobbing/assets/30723811/343b1a83-499b-414f-9c12-f7a69f664587)

**Comment by KaiAF** [comment]
Featured
