### ISSUE TITLE
Incompatible with 1.20.1

### ISSUE THREAD

**Issue by Apollounknowndev** [KaiAF/BetterHandBobbing#5]
Should be as simple as updating the fabric.mod.json to say ">=1.20" instead of "1.20".

![image](https://github.com/KaiAF/BetterHandBobbing/assets/102649729/cbaf1d69-5638-47e8-b0f1-1f0040aaa26d)

**Comment by KaiAF** [comment]
Fixed, redownload 1.5 https://modrinth.com/mod/better-hand-bobbing/version/1.5
