### ISSUE TITLE
Disable with iris shaders enabled

### ISSUE THREAD

**Issue by JoeyFab** [KaiAF/BetterHandBobbing#8]
I was wondering if you could just disable the mod with mod menu or automatically when you enable shaders so you hand at least moves. Thanks.

**Comment by KaiAF** [comment]
Sorry! I thought I did this already. I went ahead and fixed the hand bobbing not working with IrisShaders with shaders enabled. It can be downloaded [here](https://modrinth.com/mod/better-hand-bobbing/version/1.6.1).

**Comment by JoeyFab** [comment]
Thank you so much!
