### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RinixGG** [KaiAF/BetterHandBobbing#9]
https://mclo.gs/LOjAkBL

Minecraft 1.20.1
Quilt 0.19.2
BetterHandBobbing 1.6.2

**Comment by KaiAF** [comment]
I'll look into it sometime soon, thanks for reporting

**Comment by KaiAF** [comment]
Fixed, please re-download [1.6.2](https://modrinth.com/mod/better-hand-bobbing/version/1.6.2). It was ghost updated in commit [`https://github.com/KaiAF/BetterHandBobbing/commit/435b07f0bf97d0a040e63820ecdc03201191b0d5`](https://github.com/KaiAF/BetterHandBobbing/commit/435b07f0bf97d0a040e63820ecdc03201191b0d5)
